"""The generic engine: load typed artifacts, validate them, and build the bundle.

No domain knowledge lives here — the artifact types come entirely from the config.
Diagnostics carry stable PAC-NNN codes (see :mod:`fastpdlc.diagnostics`).
"""
from __future__ import annotations

import datetime
import json
import pathlib

import yaml

from .config import ArtifactType, Config
from .diagnostics import Report

_GENERATED_NOTE = (
    "AUTO-GENERATED by FastPDLC (fastpdlc build). Do not edit by hand — edit the "
    "product/ source files and rerun."
)


# ── frontmatter ──────────────────────────────────────────────────────────────
def parse_frontmatter(path: pathlib.Path) -> tuple[dict, str]:
    """Split a ``---``-delimited YAML frontmatter block from its markdown body."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}, text.strip()
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text.strip()
    meta = yaml.safe_load(parts[1]) or {}
    if not isinstance(meta, dict):
        raise ValueError(f"{path.name}: frontmatter is not a mapping")
    return meta, parts[2].strip()


def _load_type(t: ArtifactType, product_dir: pathlib.Path) -> list[dict]:
    records: list[dict] = []
    tdir = product_dir / t.dir
    if not tdir.exists():
        return records
    for path in sorted(tdir.glob("*.md")):
        meta, body = parse_frontmatter(path)
        rec = {
            "id": meta.get("id", path.stem),
            "_file": str(path.relative_to(product_dir.parent)).replace("\\", "/"),
            "body": body,
        }
        for f in t.fields:
            rec[f] = meta.get(f)
        records.append(rec)
    return records


def load(config: Config, root: str | pathlib.Path = ".") -> dict[str, list[dict]]:
    """Load every configured type into ``{type_name: [records]}``."""
    product_dir = pathlib.Path(root) / config.product_dir
    return {t.name: _load_type(t, product_dir) for t in config.types}


def _transformed_bundle(config: Config, root, registry) -> dict:
    bundle = {"note": _GENERATED_NOTE, **load(config, root)}
    if registry:
        for tf in registry.bundle_transformers:
            tf(bundle, config, pathlib.Path(root))
    return bundle


def _json_default(obj):
    """YAML parses an unquoted ``2026-02-04`` into a ``datetime.date``, which json
    cannot serialize. Dates are far too common in frontmatter (``date``, ``due``,
    ``reviewed``) to expect every author to remember quoting them, so normalise to
    ISO-8601 strings -- stable, sortable, and byte-identical across runs."""
    if isinstance(obj, (datetime.datetime, datetime.date, datetime.time)):
        return obj.isoformat()
    raise TypeError(f"cannot serialize {type(obj).__name__} into the bundle")


def _dump(bundle: dict, sort_keys: bool = True) -> str:
    return json.dumps(
        bundle, indent=2, ensure_ascii=False, sort_keys=sort_keys, default=_json_default
    ) + "\n"


def render_bundle(config: Config, root: str | pathlib.Path = ".", registry=None) -> str:
    """The exact JSON bundle string expected on disk (stable ordering + trailing NL)."""
    return _dump(_transformed_bundle(config, root, registry), config.sort_keys)


def build(config: Config, root: str | pathlib.Path = ".", registry=None) -> list[pathlib.Path]:
    """Write the generated bundle (+ any plugin extra outputs). Returns the paths written."""
    bundle = _transformed_bundle(config, root, registry)
    out = pathlib.Path(root) / config.output
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_dump(bundle, config.sort_keys), encoding="utf-8", newline="\n")
    written = [out]
    if registry:
        for rel, renderer in registry.extra_outputs:
            ep = pathlib.Path(root) / rel
            ep.parent.mkdir(parents=True, exist_ok=True)
            ep.write_text(renderer(bundle, config, pathlib.Path(root)), encoding="utf-8", newline="\n")
            written.append(ep)
    return written


# ── validation ───────────────────────────────────────────────────────────────
def _is_empty(v: object) -> bool:
    return v is None or (isinstance(v, (str, list, dict)) and len(v) == 0)


def validate(config: Config, root: str | pathlib.Path = ".", registry=None) -> Report:
    """Run schema + id + reference + staleness checks (+ any plugin checks); return a Report."""
    report = Report()
    bundle = load(config, root)
    # id sets per type, for reference resolution.
    ids_by_type = {name: {r["id"] for r in recs if r["id"]} for name, recs in bundle.items()}

    for t in config.types:
        seen: set[str] = set()
        for rec in bundle[t.name]:
            rid, where = rec["id"], rec["_file"]

            # required fields (PAC-001)
            for req in t.required:
                val = rid if req == "id" else rec.get(req)
                if _is_empty(val):
                    report.add("PAC-001", f"missing required field '{req}'", where)

            # id prefix + filename (PAC-010 / PAC-011)
            if rid:
                if t.id_prefix and not str(rid).startswith(t.id_prefix):
                    report.add("PAC-010", f"id '{rid}' must start with '{t.id_prefix}'", where)
                elif t.id_matches_filename and not where.endswith(f"/{rid}.md"):
                    report.add("PAC-011", f"id '{rid}' must match its filename ({rid}.md)", where)
                # duplicate id (PAC-012)
                if rid in seen:
                    report.add("PAC-012", f"duplicate id '{rid}' in type '{t.name}'", where)
                seen.add(rid)

            # enums (PAC-030)
            for efield, allowed in t.enums.items():
                v = rec.get(efield)
                if v is not None and v not in allowed:
                    report.add("PAC-030", f"{efield} '{v}' not in {sorted(allowed)}", where)

            # references (PAC-020)
            for ref in t.references:
                targets = ids_by_type.get(ref.to, set())
                raw = rec.get(ref.field)
                for val in (raw if isinstance(raw, list) else [raw] if raw else []):
                    if val not in targets:
                        report.add(
                            "PAC-020",
                            f"{ref.field} '{val}' does not resolve to a {ref.to} id",
                            where,
                        )

    # plugin validators — project-specific cross-file / graph checks.
    if registry:
        for v in registry.validators:
            v(bundle, config, pathlib.Path(root), report)

    # bundle staleness (PAC-060), registry-aware so transformed fields are counted.
    out = pathlib.Path(root) / config.output
    if not out.exists():
        report.add("PAC-060", f"{config.output} is missing — run: fastpdlc build")
    elif out.read_text(encoding="utf-8") != render_bundle(config, root, registry):
        report.add("PAC-060", f"{config.output} is stale — run: fastpdlc build (and commit it)")

    # extra committed outputs (e.g. a runtime catalogue) — same staleness gate.
    if registry:
        tb = _transformed_bundle(config, root, registry)
        for rel, renderer in registry.extra_outputs:
            ep = pathlib.Path(root) / rel
            expected = renderer(tb, config, pathlib.Path(root))
            if not ep.exists():
                report.add("PAC-060", f"{rel} is missing — run: fastpdlc build")
            elif ep.read_text(encoding="utf-8") != expected:
                report.add("PAC-060", f"{rel} is stale — run: fastpdlc build (and commit it)")

    return report
