"""Generate the CLI surface manifest from argparse itself.

The newsletter generator needs to know what the FastPDLC CLI actually offers, for
two reasons: to tell the model, and to reject output that invents commands. Both
were hardcoded, so adding `fastpdlc evidence` silently made the guard reject true
statements about our own tool.

This reads the real parser and writes the manifest. It is a generated artifact
committed to the repository, and `test_cli_surface_manifest_is_current` fails when
it drifts -- PAC-060 semantics applied to our own tooling, which is the argument
the product makes.

    python site/tools/gen_cli_surface.py
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "site" / "api" / "cli_surface.json"

sys.path.insert(0, str(REPO))


def _options(parser: argparse.ArgumentParser) -> list[str]:
    """Every long option the parser accepts, minus argparse's own --help."""
    flags: set[str] = set()
    for action in parser._actions:
        for opt in action.option_strings:
            if opt.startswith("--") and opt != "--help":
                flags.add(opt)
    return sorted(flags)


def build_surface() -> dict:
    from fastpdlc.cli import _build_parser

    parser = _build_parser()

    subcommands: dict[str, dict] = {}
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, sub in action.choices.items():
            subcommands[name] = {
                "help": (sub.description or "").strip()
                        or next((c.help for c in action._choices_actions if c.dest == name), "")
                        or "",
                "flags": _options(sub),
            }

    return {
        "schema": "fastpdlc-cli-surface/1",
        "note": "Generated by site/tools/gen_cli_surface.py -- do not edit by hand.",
        "global_flags": _options(parser),
        "subcommands": subcommands,
    }


def render(surface: dict) -> str:
    return json.dumps(surface, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    surface = build_surface()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(surface), encoding="utf-8", newline="\n")
    verbs = ", ".join(sorted(surface["subcommands"]))
    flags = ", ".join(surface["global_flags"])
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  subcommands : {verbs}")
    print(f"  global flags: {flags}")
    for name, meta in sorted(surface["subcommands"].items()):
        if meta["flags"]:
            print(f"  {name} flags : {', '.join(meta['flags'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
